### ISSUE TITLE
Add Treg Specificity vs. IL2Rb and IL2Ra Affinity fig

### ISSUE THREAD

**Issue by borcuttjahns** [meyer-lab/gc-cytokines#64]
Predicted specificity for Tregs vs. IL2Rb affinity for wt and reduced IL2Ra affinities.

**Comment by aarmey** [comment]
![specificity](https://user-images.githubusercontent.com/2065146/68982334-6a2f8780-07bb-11ea-99e7-ce3085283e25.png)

Darn. Doesn't look like I have the code. x-axis is b/g affinity and both should change proportionally. Dotted line is 10-fold weaker alpha affinity.
